name: secure_keypad_flutter
description: Secure Native Flutter contract for a customizable virtual keypad.
version: 0.1.0
repository: https://github.com/uulab/secure-keyboard
issue_tracker: https://github.com/uulab/secure-keyboard/issues
license: MIT

environment:
  sdk: '>=3.4.0 <4.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
