#![forbid(unsafe_code)]
#![warn(missing_docs)]

//! Native/server OPAQUE protocol boundary.
//!
//! This crate accepts password bytes only inside native or server Rust code.
//! Framework adapters must not bind these APIs directly to JavaScript, Dart,
//! or ordinary UI state. Use the secure keypad submission boundary to invoke
//! this engine inside the native layer.

use opaque_ke::{
    CipherSuite, ClientLogin, ClientLoginFinishParameters, ClientRegistration,
    ClientRegistrationFinishParameters, CredentialFinalization, CredentialRequest,
    CredentialResponse, Identifiers, RegistrationRequest, RegistrationResponse, RegistrationUpload,
    ServerLogin, ServerLoginParameters, ServerRegistration, ServerSetup,
};
use rand::rngs::OsRng;
use subtle::ConstantTimeEq;
use zeroize::Zeroize;

/// Stable protocol version for this SDK surface.
pub const PROTOCOL_VERSION: u16 = 1;
/// Stable cipher-suite identifier for persistence and downgrade checks.
pub const CIPHER_SUITE_ID: &str = "opaque-ke-4.0.1-ristretto255-tripledh-sha512-argon2";

/// OPAQUE cipher suite used by this SDK.
pub struct SecureSuite;

impl CipherSuite for SecureSuite {
    type OprfCs = opaque_ke::Ristretto255;
    type KeyExchange = opaque_ke::TripleDh<opaque_ke::Ristretto255, sha2::Sha512>;
    type Ksf = opaque_ke::argon2::Argon2<'static>;
}

/// An encoded OPAQUE message. Messages are not passwords, but must still be
/// treated as sensitive transport data and never logged.
pub struct Message(Vec<u8>);

impl Message {
    /// Copies a protocol message from transport bytes.
    #[must_use]
    pub fn from_bytes(bytes: &[u8]) -> Self {
        Self(bytes.to_vec())
    }

    /// Returns transport bytes for an HTTPS request body.
    #[must_use]
    pub fn as_bytes(&self) -> &[u8] {
        &self.0
    }
}

/// Serialized server setup. Store it in a server secret store, not in a
/// client bundle or ordinary application configuration.
pub struct ServerSetupBytes(Vec<u8>);

impl ServerSetupBytes {
    /// Generates a new server setup using the operating system CSPRNG.
    ///
    /// # Errors
    ///
    /// Returns [`AuthError::InvalidSetup`] if the generated setup cannot be
    /// serialized by the pinned OPAQUE implementation.
    pub fn generate() -> Result<Self, AuthError> {
        let mut rng = OsRng;
        let setup = ServerSetup::<SecureSuite>::new(&mut rng);
        Ok(Self(setup.serialize().to_vec()))
    }

    /// Restores a setup previously generated by this exact protocol version.
    ///
    /// # Errors
    ///
    /// Returns [`AuthError::InvalidSetup`] when the bytes fail validation.
    pub fn from_bytes(bytes: &[u8]) -> Result<Self, AuthError> {
        ServerSetup::<SecureSuite>::deserialize(bytes).map_err(|_| AuthError::InvalidSetup)?;
        Ok(Self(bytes.to_vec()))
    }

    fn decode(&self) -> Result<ServerSetup<SecureSuite>, AuthError> {
        ServerSetup::<SecureSuite>::deserialize(&self.0).map_err(|_| AuthError::InvalidSetup)
    }

    /// Returns serialized setup bytes for secret-store persistence.
    #[must_use]
    pub fn as_bytes(&self) -> &[u8] {
        &self.0
    }
}

/// A server-side OPAQUE credential file. It is password-equivalent sensitive
/// material and must be encrypted or access-controlled at rest.
pub struct CredentialFile(Vec<u8>);

impl CredentialFile {
    /// Restores a credential file after checking its encoding.
    ///
    /// # Errors
    ///
    /// Returns [`AuthError::InvalidCredentialFile`] when the bytes fail validation.
    pub fn from_bytes(bytes: &[u8]) -> Result<Self, AuthError> {
        ServerRegistration::<SecureSuite>::deserialize(bytes)
            .map_err(|_| AuthError::InvalidCredentialFile)?;
        Ok(Self(bytes.to_vec()))
    }

    /// Returns serialized credential bytes for protected server storage.
    #[must_use]
    pub fn as_bytes(&self) -> &[u8] {
        &self.0
    }

    fn decode(&self) -> Result<ServerRegistration<SecureSuite>, AuthError> {
        ServerRegistration::<SecureSuite>::deserialize(&self.0)
            .map_err(|_| AuthError::InvalidCredentialFile)
    }
}

/// A secret output from OPAQUE, such as a session key or export key.
pub struct SecretOutput(Vec<u8>);

impl SecretOutput {
    /// Returns the length without revealing secret bytes.
    #[must_use]
    pub fn len(&self) -> usize {
        self.0.len()
    }

    /// Returns whether this output is empty.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.0.is_empty()
    }

    /// Compares two outputs in constant time.
    #[must_use]
    pub fn constant_time_eq(&self, other: &Self) -> bool {
        self.0.ct_eq(&other.0).into()
    }

    /// Provides bytes to native/server cryptographic code for immediate use.
    ///
    /// This method must not be exposed through a framework bridge or used to
    /// create logs, strings, JSON, analytics fields, or persistent plaintext.
    pub fn with_bytes<R>(&self, operation: impl FnOnce(&[u8]) -> R) -> R {
        operation(&self.0)
    }
}

impl Drop for SecretOutput {
    fn drop(&mut self) {
        self.0.zeroize();
    }
}

/// Client state retained between the first and second registration messages.
pub struct ClientRegistrationState(ClientRegistration<SecureSuite>);
/// Client state retained between the first and second login messages.
pub struct ClientLoginState(ClientLogin<SecureSuite>);
/// Server state retained between the first and second login messages.
pub struct ServerLoginState(ServerLogin<SecureSuite>);

/// Native-only client login state that retains the sealed password until the
/// second OPAQUE message. Never expose this type through a framework bridge.
pub struct NativeClientLoginState {
    state: Option<ClientLogin<SecureSuite>>,
    password: Vec<u8>,
}

impl Drop for NativeClientLoginState {
    fn drop(&mut self) {
        self.password.zeroize();
    }
}

/// Errors that never include password or secret bytes.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum AuthError {
    /// A protocol message failed validation.
    Protocol,
    /// A setup blob failed validation.
    InvalidSetup,
    /// A credential file failed validation.
    InvalidCredentialFile,
    /// Authentication proof verification failed.
    InvalidLogin,
}

impl core::fmt::Display for AuthError {
    fn fmt(&self, formatter: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        formatter.write_str(match self {
            Self::Protocol => "opaque protocol error",
            Self::InvalidSetup => "invalid server setup",
            Self::InvalidCredentialFile => "invalid credential file",
            Self::InvalidLogin => "invalid login",
        })
    }
}

impl std::error::Error for AuthError {}

/// Starts client registration. The password is borrowed only for the protocol call.
///
/// # Errors
///
/// Returns [`AuthError::Protocol`] when the pinned OPAQUE implementation rejects
/// the password input or cannot create a registration request.
pub fn client_registration_start(
    password: &[u8],
) -> Result<(ClientRegistrationState, Message), AuthError> {
    let mut rng = OsRng;
    let result = ClientRegistration::<SecureSuite>::start(&mut rng, password)
        .map_err(|_| AuthError::Protocol)?;
    Ok((
        ClientRegistrationState(result.state),
        Message(result.message.serialize().to_vec()),
    ))
}

/// Starts server registration for a public credential identifier.
///
/// # Errors
///
/// Returns [`AuthError::InvalidSetup`] for an invalid setup or
/// [`AuthError::Protocol`] for an invalid request.
pub fn server_registration_start(
    setup: &ServerSetupBytes,
    request: &Message,
    credential_identifier: &[u8],
) -> Result<Message, AuthError> {
    let setup = setup.decode()?;
    let request = RegistrationRequest::<SecureSuite>::deserialize(request.as_bytes())
        .map_err(|_| AuthError::Protocol)?;
    let result = ServerRegistration::<SecureSuite>::start(&setup, request, credential_identifier)
        .map_err(|_| AuthError::Protocol)?;
    Ok(Message(result.message.serialize().to_vec()))
}

/// Finishes client registration and returns the upload and client export key.
///
/// # Errors
///
/// Returns [`AuthError::Protocol`] if the response or registration state fails
/// the pinned OPAQUE checks.
pub fn client_registration_finish(
    state: ClientRegistrationState,
    password: &[u8],
    response: &Message,
    client_identifier: &[u8],
    server_identifier: &[u8],
) -> Result<(Message, SecretOutput), AuthError> {
    let response = RegistrationResponse::<SecureSuite>::deserialize(response.as_bytes())
        .map_err(|_| AuthError::Protocol)?;
    let mut rng = OsRng;
    let result = state
        .0
        .finish(
            &mut rng,
            password,
            response,
            ClientRegistrationFinishParameters::new(
                Identifiers {
                    client: Some(client_identifier),
                    server: Some(server_identifier),
                },
                None,
            ),
        )
        .map_err(|_| AuthError::Protocol)?;
    Ok((
        Message(result.message.serialize().to_vec()),
        SecretOutput(result.export_key.to_vec()),
    ))
}

/// Finalizes a server credential file from the client upload.
///
/// # Errors
///
/// Returns [`AuthError::Protocol`] if the upload is malformed.
pub fn server_registration_finish(upload: &Message) -> Result<CredentialFile, AuthError> {
    let upload = RegistrationUpload::<SecureSuite>::deserialize(upload.as_bytes())
        .map_err(|_| AuthError::Protocol)?;
    let file = ServerRegistration::<SecureSuite>::finish(upload);
    Ok(CredentialFile(file.serialize().to_vec()))
}

/// Starts client login.
///
/// # Errors
///
/// Returns [`AuthError::Protocol`] when the pinned OPAQUE implementation cannot
/// create a login request.
pub fn client_login_start(password: &[u8]) -> Result<(ClientLoginState, Message), AuthError> {
    let mut rng = OsRng;
    let result =
        ClientLogin::<SecureSuite>::start(&mut rng, password).map_err(|_| AuthError::Protocol)?;
    Ok((
        ClientLoginState(result.state),
        Message(result.message.serialize().to_vec()),
    ))
}

/// Starts client login directly from a secure keypad submission.
///
/// # Errors
///
/// Returns [`AuthError::Protocol`] when the pinned OPAQUE implementation cannot
/// create a login request.
#[allow(clippy::needless_pass_by_value)]
pub fn client_login_start_from_submission(
    submission: secure_core::Submission,
) -> Result<(NativeClientLoginState, Message), AuthError> {
    let mut password = Vec::new();
    submission.with_native_bytes(|bytes| password.extend_from_slice(bytes));
    let mut rng = OsRng;
    let result =
        ClientLogin::<SecureSuite>::start(&mut rng, &password).map_err(|_| AuthError::Protocol)?;
    Ok((
        NativeClientLoginState {
            state: Some(result.state),
            password,
        },
        Message(result.message.serialize().to_vec()),
    ))
}

/// Starts server login. Pass `None` for a missing user to keep enumeration
/// behavior indistinguishable from a registered user.
///
/// # Errors
///
/// Returns [`AuthError::InvalidSetup`], [`AuthError::InvalidCredentialFile`], or
/// [`AuthError::Protocol`] when setup, credential, or request validation fails.
pub fn server_login_start(
    setup: &ServerSetupBytes,
    credential_file: Option<&CredentialFile>,
    request: &Message,
    credential_identifier: &[u8],
    client_identifier: &[u8],
    server_identifier: &[u8],
) -> Result<(Message, ServerLoginState), AuthError> {
    let setup = setup.decode()?;
    let credential_file = credential_file.map(CredentialFile::decode).transpose()?;
    let request = CredentialRequest::<SecureSuite>::deserialize(request.as_bytes())
        .map_err(|_| AuthError::Protocol)?;
    let mut rng = OsRng;
    let result = ServerLogin::<SecureSuite>::start(
        &mut rng,
        &setup,
        credential_file,
        request,
        credential_identifier,
        ServerLoginParameters {
            context: None,
            identifiers: Identifiers {
                client: Some(client_identifier),
                server: Some(server_identifier),
            },
        },
    )
    .map_err(|_| AuthError::Protocol)?;
    Ok((
        Message(result.message.serialize().to_vec()),
        ServerLoginState(result.state),
    ))
}

/// Finishes client login and returns finalization plus the client session key.
///
/// # Errors
///
/// Returns [`AuthError::InvalidLogin`] when the password proof is invalid, or
/// [`AuthError::Protocol`] when the response is malformed.
pub fn client_login_finish(
    state: ClientLoginState,
    password: &[u8],
    response: &Message,
    client_identifier: &[u8],
    server_identifier: &[u8],
) -> Result<(Message, SecretOutput), AuthError> {
    let response = CredentialResponse::<SecureSuite>::deserialize(response.as_bytes())
        .map_err(|_| AuthError::Protocol)?;
    let mut rng = OsRng;
    let result = state
        .0
        .finish(
            &mut rng,
            password,
            response,
            ClientLoginFinishParameters::new(
                None,
                Identifiers {
                    client: Some(client_identifier),
                    server: Some(server_identifier),
                },
                None,
            ),
        )
        .map_err(|_| AuthError::InvalidLogin)?;
    Ok((
        Message(result.message.serialize().to_vec()),
        SecretOutput(result.session_key.to_vec()),
    ))
}

/// Finishes a native-only login without returning the password to the caller.
///
/// # Errors
///
/// Returns [`AuthError::InvalidLogin`] when the password proof is invalid, or
/// [`AuthError::Protocol`] when the response is malformed.
pub fn client_login_finish_from_native_state(
    mut state: NativeClientLoginState,
    response: &Message,
    client_identifier: &[u8],
    server_identifier: &[u8],
) -> Result<(Message, SecretOutput), AuthError> {
    let response = CredentialResponse::<SecureSuite>::deserialize(response.as_bytes())
        .map_err(|_| AuthError::Protocol)?;
    let mut rng = OsRng;
    let result = state
        .state
        .take()
        .ok_or(AuthError::InvalidLogin)?
        .finish(
            &mut rng,
            &state.password,
            response,
            ClientLoginFinishParameters::new(
                None,
                Identifiers {
                    client: Some(client_identifier),
                    server: Some(server_identifier),
                },
                None,
            ),
        )
        .map_err(|_| AuthError::InvalidLogin)?;
    Ok((
        Message(result.message.serialize().to_vec()),
        SecretOutput(result.session_key.to_vec()),
    ))
}

/// Finishes server login and returns the server session key.
///
/// # Errors
///
/// Returns [`AuthError::InvalidLogin`] when client proof verification fails, or
/// [`AuthError::Protocol`] when the finalization message is malformed.
pub fn server_login_finish(
    state: ServerLoginState,
    finalization: &Message,
    client_identifier: &[u8],
    server_identifier: &[u8],
) -> Result<SecretOutput, AuthError> {
    let finalization = CredentialFinalization::<SecureSuite>::deserialize(finalization.as_bytes())
        .map_err(|_| AuthError::Protocol)?;
    let result = state
        .0
        .finish(
            finalization,
            ServerLoginParameters {
                context: None,
                identifiers: Identifiers {
                    client: Some(client_identifier),
                    server: Some(server_identifier),
                },
            },
        )
        .map_err(|_| AuthError::InvalidLogin)?;
    Ok(SecretOutput(result.session_key.to_vec()))
}
